
services:
  web:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - 8501:8501
    env_file:
      - .env
    restart: always
    depends_on:
      - api

  api:
    build: ./api
    command: uvicorn api.app:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./:/code/
    ports:
      - 8000:8000
    env_file:
      - .env
