AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Core infrastructure for Celebrity Comparsion App

Parameters:
  BucketName:
    Type: String

Resources:
  CelebComparsionBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName