version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - 5432:5432
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db/__data/:/docker-entrypoint-initdb.d/
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  postgres_data: