version: '3.8'

services:
  web:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 8501:8501
    env_file:
      - .env
    restart: always
    depends_on:
      - db
      - api

  api:
    build: ./api
    command: uvicorn api.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./:/code/
    ports:
      - 8001:8000
    env_file:
      - .env
    environment:
      - DATABASE_URI=postgresql://root:root@db/test_db
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - 5432:5432
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./app/__data/data.csv:/docker-entrypoint-initdb.d/data.csv
      - ./app/db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  postgres_data: